
// The following ifdef block is the standard way of creating macros which make exporting 
// from a DLL simpler. All files within this DLL are compiled with the MWIC_32_EXPORTS
// symbol defined on the command line. this symbol should not be defined on any project
// that uses this DLL. This way any other project whose source files include this file see 
// MWIC_32_API functions as being imported from a DLL, wheras this DLL sees symbols
// defined with this macro as being exported.

#ifndef _MWIC_32_H
#define _MWIC_32_H

typedef HANDLE (__stdcall * pic_init)(__int16, unsigned long);
typedef HANDLE (__stdcall * pauto_init)(__int16, unsigned long);
typedef __int16 (__stdcall * pic_exit)(HANDLE);
typedef __int16 (__stdcall * psrd_ver)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pset_baud)(HANDLE, unsigned long);
typedef __int16 (__stdcall * pcmp_dvsc)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * psrd_dvsc)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_dvsc)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * psetsc_md)(HANDLE, __int16);
typedef __int16 (__stdcall * pturn_on)(HANDLE);
typedef __int16 (__stdcall * pturn_off)(HANDLE);
typedef __int16 (__stdcall * pauto_pull)(HANDLE);
typedef __int16 (__stdcall * pget_status)(HANDLE,__int16*);
typedef __int16 (__stdcall * pget_status_DPEx)(HANDLE,unsigned char,__int16*);
typedef __int16 (__stdcall * pdv_beep)(HANDLE, __int16);
typedef __int16 (__stdcall * pswr_eeprom)(HANDLE, __int16,__int16, unsigned char*);
typedef __int16 (__stdcall * psrd_eeprom)(HANDLE, __int16,__int16, unsigned char*);
typedef __int16 (__stdcall * psrd_snr)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pval_read)(HANDLE,unsigned long*);
typedef __int16 (__stdcall * pval_inc)(HANDLE, unsigned long);
typedef __int16 (__stdcall * pval_dec)(HANDLE, unsigned long);
typedef __int16 (__stdcall * pval_set)(HANDLE, unsigned long);
typedef __int32 (__stdcall * pchk_baud)(__int16);
typedef __int16 (__stdcall * pchk_card)(HANDLE);
typedef __int16 (__stdcall * pic_encrypt)(char*, char*, unsigned short, char*);
typedef __int16 (__stdcall * pic_decrypt)(char*, char*, unsigned short, char*);
typedef unsigned long (__stdcall * pDES_Encrypt)(unsigned char*,__int16, unsigned char*, unsigned long, unsigned char*);
typedef unsigned long (__stdcall * pDES_Decrypt)(unsigned char*,__int16, unsigned char*, unsigned long, unsigned char*);
typedef __int16 (__stdcall * plib_ver)(char*);
typedef __int16 (__stdcall * pasc_hex)(unsigned char*, unsigned char*, long);
typedef __int16 (__stdcall * phex_asc)(unsigned char*, unsigned char*, long);
typedef __int16 (__stdcall * pasc_asc)(unsigned char*, unsigned char*, long);
typedef __int16 (__stdcall * pfloat_uchar)(float,unsigned char*);
typedef __int16 (__stdcall * puchar_float)(unsigned char*, float*);
typedef __int16 (__stdcall * pshort_uchar)(short i, unsigned char*);
typedef __int16 (__stdcall * puchar_short)(unsigned char*, short*);
typedef __int16 (__stdcall * plong_uchar)(long, unsigned char*);
typedef __int16 (__stdcall * puchar_long)(unsigned char*, long*);
typedef __int16 (__stdcall * psrd_4404)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_4404)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pcsc_4404)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pwsc_4404)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsc_4404)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsct_4404)(HANDLE, __int16*);
typedef __int16 (__stdcall * pcesc_4404)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pwesc_4404)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * presc_4404)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * presct_4404)(HANDLE, __int16*);
typedef __int16 (__stdcall * pser_4404)(HANDLE, __int16, __int16);
typedef __int16 (__stdcall * pfakefus_4404)(HANDLE, __int16);
typedef __int16 (__stdcall * pclrpr_4404)(HANDLE);
typedef __int16 (__stdcall * pclrrd_4404)(HANDLE);
typedef __int16 (__stdcall * ppsnl_4404)(HANDLE);
typedef __int16 (__stdcall * pchk_4404)(HANDLE);
typedef __int16 (__stdcall * psrd_4406)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_4406)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pcsc_4406)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pwsc_4406)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsc_4406)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsct_4406)(HANDLE, __int16*);
typedef __int16 (__stdcall * peswc_4406)(HANDLE, __int16);
typedef __int16 (__stdcall * ppsnl_4406)(HANDLE);
typedef __int16 (__stdcall * pchk_4406)(HANDLE);
typedef __int16 (__stdcall * psrd_102)(HANDLE, __int16, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_102)(HANDLE, __int16, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pser_102)(HANDLE, __int16, __int16, __int16);
typedef __int16 (__stdcall * pcsc_102)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsc_102)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pwsc_102)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsct_102)(HANDLE, __int16*);
typedef __int16 (__stdcall * pcesc_102)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * presc_102)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pwesc_102)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * presct_102)(HANDLE, __int16, __int16*);
typedef __int16 (__stdcall * pclrpr_102)(HANDLE, __int16);
typedef __int16 (__stdcall * pclrrd_102)(HANDLE, __int16);
typedef __int16 (__stdcall * pfakefus_102)(HANDLE, __int16);
typedef __int16 (__stdcall * ppsnl_102)(HANDLE);
typedef __int16 (__stdcall * pchk_102)(HANDLE);
typedef __int16 (__stdcall * psrd_1604)(HANDLE, __int16, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_1604)(HANDLE, __int16, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pser_1604)(HANDLE, __int16, __int16, __int16);
typedef __int16 (__stdcall * pcsc_1604)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * prsc_1604)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pwsc_1604)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * prsct_1604)(HANDLE, __int16, __int16*);
typedef __int16 (__stdcall * pcesc_1604)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * presc_1604)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pwesc_1604)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * presct_1604)(HANDLE, __int16, __int16*);
typedef __int16 (__stdcall * pclrpr_1604)(HANDLE, __int16);
typedef __int16 (__stdcall * pclrrd_1604)(HANDLE, __int16);
typedef __int16 (__stdcall * pfakefus_1604)(HANDLE, __int16);
typedef __int16 (__stdcall * ppsnl_1604)(HANDLE);
typedef __int16 (__stdcall * pchk_1604)(HANDLE);
typedef __int16 (__stdcall * psrd_1604b)(HANDLE, __int16, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_1604b)(HANDLE, __int16, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pser_1604b)(HANDLE, __int16, __int16, __int16);
typedef __int16 (__stdcall * pcsc_1604b)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * prsc_1604b)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pwsc_1604b)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * prsct_1604b)(HANDLE, __int16, __int16*);
typedef __int16 (__stdcall * pcesc_1604b)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * presc_1604b)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pwesc_1604b)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * presct_1604b)(HANDLE, __int16, __int16*);
typedef __int16 (__stdcall * pclrpr_1604b)(HANDLE, __int16);
typedef __int16 (__stdcall * pclrrd_1604b)(HANDLE, __int16);
typedef __int16 (__stdcall * pfakefus_1604b)(HANDLE, __int16);
typedef __int16 (__stdcall * ppsnl_1604b)(HANDLE);
typedef __int16 (__stdcall * pchk_1604b)(HANDLE);
typedef __int16 (__stdcall * pswr_24c01a)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * psrd_24c01a)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pchk_24c01a)(HANDLE);
typedef __int16 (__stdcall * pswr_24c02)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * psrd_24c02)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pchk_24c02)(HANDLE);
typedef __int16 (__stdcall * pswr_24c04)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * psrd_24c04)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pchk_24c04)(HANDLE);
typedef __int16 (__stdcall * pswr_24c08)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * psrd_24c08)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pchk_24c08)(HANDLE);
typedef __int16 (__stdcall * pswr_24c16)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * psrd_24c16)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pchk_24c16)(HANDLE);
typedef __int16 (__stdcall * pswr_24c32)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * psrd_24c32)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pchk_24c32)(HANDLE);
typedef __int16 (__stdcall * pswr_24c64)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * psrd_24c64)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pchk_24c64)(HANDLE);
typedef __int16 (__stdcall * psrd_4418)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_4418)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * prdwpb_4418)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pwrwpb_4418)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * ppwr_4418)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pchk_4418)(HANDLE);
typedef __int16 (__stdcall * psrd_4428)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_4428)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * prdwpb_4428)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pwrwpb_4428)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * ppwr_4428)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pcsc_4428)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pwsc_4428)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsc_4428)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsct_4428)(HANDLE, __int16*);
typedef __int16 (__stdcall * pchk_4428)(HANDLE);
typedef __int16 (__stdcall * psrd_4442)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pswr_4442)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pprd_4442)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * ppwr_4442)(HANDLE, __int16, __int16, unsigned char*);
typedef __int16 (__stdcall * pcsc_4442)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * pwsc_4442)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsc_4442)(HANDLE, __int16, unsigned char*);
typedef __int16 (__stdcall * prsct_4442)(HANDLE, __int16*);
typedef __int16 (__stdcall * pchk_4442)(HANDLE);
typedef __int16 (__stdcall * psrd_4432)(HANDLE, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * pswr_4432)(HANDLE, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * pprd_4432)(HANDLE, __int16, unsigned char *);
typedef __int16 (__stdcall * ppwr_4432)(HANDLE, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * pchk_4432)(HANDLE);
typedef __int16 (__stdcall * psrd_45d041)(HANDLE, __int16, __int16, unsigned long, unsigned char *);
typedef __int16 (__stdcall * pswr_45d041)(HANDLE, __int16, __int16, unsigned long, unsigned char *);
typedef __int16 (__stdcall * prdstrg_45d041)(HANDLE, unsigned char *);
typedef __int16 (__stdcall * pchk_45d041)(HANDLE);
typedef __int16 (__stdcall * pswr_93c46a)(HANDLE,__int16, __int16, unsigned char *);
typedef __int16 (__stdcall * psrd_93c46a)(HANDLE,__int16, __int16, unsigned char *);
typedef __int16 (__stdcall * peral_93c46a)(HANDLE);
typedef __int16 (__stdcall * pchk_93c46a)(HANDLE);
typedef __int16 (__stdcall * pswr_93c46)(HANDLE,__int16, __int16, unsigned char *);
typedef __int16 (__stdcall * psrd_93c46)(HANDLE,__int16, __int16, unsigned char *);
typedef __int16 (__stdcall * peral_93c46)(HANDLE);
typedef __int16 (__stdcall * pchk_93c46)(HANDLE);
typedef __int16 (__stdcall * pcpu_reset)(HANDLE,unsigned char *);
typedef __int16 (__stdcall * pcpu_protocol)(HANDLE,__int16, unsigned char *, unsigned char *);
typedef __int16 (__stdcall * pcpu_comres)(HANDLE,__int16, unsigned char *, unsigned char *);
typedef __int16 (__stdcall * pset_card_baud)(HANDLE, unsigned char,unsigned char);
typedef __int16 (__stdcall * psam_power_on)(HANDLE);
typedef __int16 (__stdcall * psam_power_down)(HANDLE);
typedef __int16 (__stdcall * psam_reset)(HANDLE,__int16 *,unsigned char *);
typedef __int16 (__stdcall * psam_select)(HANDLE, unsigned char);
typedef __int16 (__stdcall * psam_protocol)(HANDLE,__int16, unsigned char *, unsigned char *);
typedef __int16 (__stdcall * psam_comres)(HANDLE,__int16, unsigned char *, unsigned char *);
typedef __int16 (__stdcall * psam_slt_power_on)(HANDLE,unsigned char);
typedef __int16 (__stdcall * psam_slt_power_down)(HANDLE,unsigned char);
typedef __int16 (__stdcall * psam_slt_reset)(HANDLE,unsigned char,__int16 *,unsigned char *);
typedef __int16 (__stdcall * psam_slt_protocol)(HANDLE,unsigned char,__int16, unsigned char *, __int16 *,unsigned char *);
typedef __int16 (__stdcall * preset_1608)(HANDLE,__int16, unsigned char *);
typedef __int16 (__stdcall * pinit_auth_1608)(HANDLE,__int16, unsigned char *);
typedef __int16 (__stdcall * pcallsrd_1608)(HANDLE,__int16,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * psrd_1608)(HANDLE,__int16,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * psrfus_1608)(HANDLE,__int16,unsigned char *);
typedef __int16 (__stdcall * pcallswr_1608)(HANDLE,__int16,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * pswr_1608)(HANDLE,__int16,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * pcsc_1608)(HANDLE,__int16,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * ppsnl_1608)(HANDLE);
typedef __int16 (__stdcall * pwsc_1608)(HANDLE,__int16,__int16, __int16,unsigned char *);
typedef __int16 (__stdcall * prsc_1608)(HANDLE,__int16,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * prsct_1608)(HANDLE,__int16,__int16, __int16,unsigned char *);
typedef __int16 (__stdcall * prac_1608)(HANDLE,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * pwac_1608)(HANDLE,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * pchk_1608)(HANDLE);
typedef __int16 (__stdcall * psrdconfig_1608)(HANDLE,__int16,__int16,unsigned char *);
typedef __int16 (__stdcall * pswrconfig_1608)(HANDLE,__int16,__int16,unsigned char *);
typedef void (__stdcall * pAuthenticate)(unsigned char *,unsigned char *);
typedef void (__stdcall * pSetInit)(unsigned char *, unsigned char *,unsigned char *);
typedef __int16 (__stdcall * preset_153)(HANDLE, __int16, unsigned char *);
typedef __int16 (__stdcall * pinit_auth_153)(HANDLE, __int16, unsigned char *);
typedef __int16 (__stdcall * pchk_153)(HANDLE);
typedef __int16 (__stdcall * psrd_153)(HANDLE, __int16, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * pswr_153)(HANDLE, __int16, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * psrdconfig_153)(HANDLE, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * pswrconfig_153)(HANDLE, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * prac_153)(HANDLE, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * pwac_153)(HANDLE, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * prautht_153)(HANDLE, __int16, unsigned char *);
typedef __int16 (__stdcall * prdcr_153)(HANDLE, __int16, unsigned char *);
typedef __int16 (__stdcall * pwdcr_153)(HANDLE, __int16, unsigned char *);
typedef __int16 (__stdcall * pcsc_153)(HANDLE, __int16, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * prsc_153)(HANDLE, __int16, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * pwsc_153)(HANDLE, __int16, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * prsct_153)(HANDLE, __int16, __int16, __int16, unsigned char *);
typedef __int16 (__stdcall * psrfus_153)(HANDLE, __int16, unsigned char *);
typedef __int16 (__stdcall * pswfus_153)(HANDLE, unsigned char);
typedef __int16 (__stdcall * ppsnl_153)(HANDLE);
typedef unsigned char (__stdcall * pxor)(unsigned char,unsigned char);
typedef unsigned char (__stdcall * pck_bcc)(__int16, unsigned char *);
typedef unsigned char (__stdcall * pcr_bcc)(__int16, unsigned char *);
typedef unsigned char (__stdcall * pcomm_bcc)(__int16, unsigned char *);
typedef __int16 (__stdcall * psrd_ssf1101)(HANDLE,__int16,__int16,long, unsigned char *);
typedef __int16 (__stdcall * pswr_ssf1101)(HANDLE,__int16,__int16,long, unsigned char *);
typedef __int16 (__stdcall * pchk_ssf1101)(HANDLE);
typedef __int16 (__stdcall * peral_ssf1101)(HANDLE);

#endif